const Countries = [
  {
    id: 'US',
    code: 'USA',
    name: 'United States',
    provinces: [
      {
        geoName: 'Armed Forces Americas',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AA',
        abbreviation: 'AA',
      },
      {
        geoName: 'Armed Forces Europe',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AE',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AE',
        abbreviation: 'AE',
      },
      {
        geoName: 'Alaska',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AK',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AK',
        abbreviation: 'AK',
      },
      {
        geoName: 'Alabama',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AL',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AL',
        abbreviation: 'AL',
      },
      {
        geoName: 'Armed Forces Pacific',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AP',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AP',
        abbreviation: 'AP',
      },
      {
        geoName: 'Arkansas',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AR',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AR',
        abbreviation: 'AR',
      },
      {
        geoName: 'Arizona',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'AZ',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'AZ',
        abbreviation: 'AZ',
      },
      {
        geoName: 'California',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'CA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'CA',
        abbreviation: 'CA',
      },
      {
        geoName: 'Colorado',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'CO',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'CO',
        abbreviation: 'CO',
      },
      {
        geoName: 'Connecticut',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'CT',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'CT',
        abbreviation: 'CT',
      },
      {
        geoName: 'District of Columbia',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'DC',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'DC',
        abbreviation: 'DC',
      },
      {
        geoName: 'Delaware',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'DE',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'DE',
        abbreviation: 'DE',
      },
      {
        geoName: 'Florida',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'FL',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'FL',
        abbreviation: 'FL',
      },
      {
        geoName: 'Georgia',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'GA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'GA',
        abbreviation: 'GA',
      },
      {
        geoName: 'Guam',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'GU',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'GU',
        abbreviation: 'GU',
      },
      {
        geoName: 'Hawaii',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'HI',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'HI',
        abbreviation: 'HI',
      },
      {
        geoName: 'Iowa',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'IA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'IA',
        abbreviation: 'IA',
      },
      {
        geoName: 'Idaho',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'ID',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'ID',
        abbreviation: 'ID',
      },
      {
        geoName: 'Illinois',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'IL',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'IL',
        abbreviation: 'IL',
      },
      {
        geoName: 'Indiana',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'IN',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'IN',
        abbreviation: 'IN',
      },
      {
        geoName: 'Kansas',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'KS',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'KS',
        abbreviation: 'KS',
      },
      {
        geoName: 'Kentucky',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'KY',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'KY',
        abbreviation: 'KY',
      },
      {
        geoName: 'Louisiana',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'LA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'LA',
        abbreviation: 'LA',
      },
      {
        geoName: 'Massachusetts',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MA',
        abbreviation: 'MA',
      },
      {
        geoName: 'Maryland',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MD',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MD',
        abbreviation: 'MD',
      },
      {
        geoName: 'Maine',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'ME',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'ME',
        abbreviation: 'ME',
      },
      {
        geoName: 'Michigan',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MI',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MI',
        abbreviation: 'MI',
      },
      {
        geoName: 'Minnesota',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MN',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MN',
        abbreviation: 'MN',
      },
      {
        geoName: 'Missouri',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MO',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MO',
        abbreviation: 'MO',
      },
      {
        geoName: 'Mississippi',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MS',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MS',
        abbreviation: 'MS',
      },
      {
        geoName: 'Montana',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'MT',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'MT',
        abbreviation: 'MT',
      },
      {
        geoName: 'North Carolina',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NC',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NC',
        abbreviation: 'NC',
      },
      {
        geoName: 'North Dakota',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'ND',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'ND',
        abbreviation: 'ND',
      },
      {
        geoName: 'Nebraska',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NE',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NE',
        abbreviation: 'NE',
      },
      {
        geoName: 'New Hampshire',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NH',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NH',
        abbreviation: 'NH',
      },
      {
        geoName: 'New Jersey',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NJ',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NJ',
        abbreviation: 'NJ',
      },
      {
        geoName: 'New Mexico',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NM',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NM',
        abbreviation: 'NM',
      },
      {
        geoName: 'Nevada',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NV',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NV',
        abbreviation: 'NV',
      },
      {
        geoName: 'New York',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'NY',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'NY',
        abbreviation: 'NY',
      },
      {
        geoName: 'Ohio',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'OH',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'OH',
        abbreviation: 'OH',
      },
      {
        geoName: 'Oklahoma',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'OK',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'OK',
        abbreviation: 'OK',
      },
      {
        geoName: 'Oregon',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'OR',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'OR',
        abbreviation: 'OR',
      },
      {
        geoName: 'Pennsylvania',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'PA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'PA',
        abbreviation: 'PA',
      },
      {
        geoName: 'Puerto Rico',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'PR',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'PR',
        abbreviation: 'PR',
      },
      {
        geoName: 'Rhode Island',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'RI',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'RI',
        abbreviation: 'RI',
      },
      {
        geoName: 'South Carolina',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'SC',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'SC',
        abbreviation: 'SC',
      },
      {
        geoName: 'South Dakota',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'SD',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'SD',
        abbreviation: 'SD',
      },
      {
        geoName: 'Tennessee',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'TN',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'TN',
        abbreviation: 'TN',
      },
      {
        geoName: 'Texas',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'TX',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'TX',
        abbreviation: 'TX',
      },
      {
        geoName: 'Utah',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'UT',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'UT',
        abbreviation: 'UT',
      },
      {
        geoName: 'Virginia',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'VA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'VA',
        abbreviation: 'VA',
      },
      {
        geoName: 'Virgin Islands',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'VI',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'VI',
        abbreviation: 'VI',
      },
      {
        geoName: 'Vermont',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'VT',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'VT',
        abbreviation: 'VT',
      },
      {
        geoName: 'Washington',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'WA',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'WA',
        abbreviation: 'WA',
      },
      {
        geoName: 'Wisconsin',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'WI',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'WI',
        abbreviation: 'WI',
      },
      {
        geoName: 'West Virginia',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'WV',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'WV',
        abbreviation: 'WV',
      },
      {
        geoName: 'Wyoming',
        geoIdFrom: 'USA',
        geoTypeId: 'STATE',
        geoId: 'WY',
        geoAssocTypeId: 'REGIONS',
        geoCode: 'WY',
        abbreviation: 'WY',
      },
    ],
  },
];

export default Countries;
